### ISSUE TITLE
RTB 3.14.0 installation failed on Ubuntu 24.04

### ISSUE THREAD

**Issue by quade0** [moloch--/RootTheBox#640]
I tried to install RTB Releases 3.14.0 on Ubuntu 24.04 LTS Server with sqlite database.
The installation step with the "setup/depends.sh" script failed, because needed pip3 packages from "./setup/requirements.txt" are not available anymore.

Some of them are now available as apt packages:

- python3-tornado
- python3-pbkdf2
- python3-pymysql
- python3-binary-memcached
- python3-dateutil
- python3-defusedxml
- python3-netaddr
- python3-nose
- python3-future
- python3-sqlalchemy
- python3-alembic
- python3-setuptools-rust
- python3-msal
- python3-requests
- python3-pillow

Other required packages from "setup/depends.sh" that are available

- build-essential
- zlib1g-dev
- memcached
- rustc
- sqlite3
- libsqlite3-dev

No apt or pip3 package alternative found for these "./setup/requirements.txt" candidates:

- python-resize-image
- enum34
- mysqlclient
- rocketchat_API

Initialize the database tables failed, still a Module is missing

```shell
./rootthebox.py --setup=prod --sql-dialect=sqlite
``` 
Shell output:

```shell
[*] 19:39:09 : Creating the database ...
Traceback (most recent call last):
  File "/opt/RTB/./rootthebox.py", line 1223, in <module>
    setup()
  File "/opt/RTB/./rootthebox.py", line 98, in setup
    from setup.create_database import create_tables, engine, metadata
  File "/opt/RTB/setup/create_database.py", line 21, in <module>
    from models import engine
  File "/opt/RTB/models/__init__.py", line 117, in <module>
    from models.Box import Box
  File "/opt/RTB/models/Box.py", line 34, in <module>
    from resizeimage import resizeimage
ModuleNotFoundError: No module named 'resizeimage'
``` 

Any idea how to fix?

**Comment by eljeffeg** [comment]
It's been a while since I build it on base hardware.  I'd suggest maybe running it in a container.  I did just push up a new branch for Python 3.13 build on bookworm (Debian), so I think that would apply to Ubuntu.  Needs testing if you want to try it.

https://github.com/moloch--/RootTheBox/tree/3.15.x

**Comment by eljeffeg** [comment]
I updated the depends.sh and looks like it's working on Ubuntu 24.04.

**Comment by quade0** [comment]
Thank you very much for your fast response.

I have still some issues.
Steps to reproduce:



```shell
sudo su -
cd /opt/
git clone git://github.com/moloch--/RootTheBox.git
git clone --depth=1 --branch 3.15.x https://github.com/moloch--/RootTheBox.git
cd RootTheBox/
./setup/depends.sh  -y SKIP  # non-interactive mode
``` 
The script asks to add the universe repo (add-apt-repository universe)
mysql-server is installed by default, but I like to use sqlite3

```shell
pip3 install -r ./setup/requirements.txt --upgrade
```
Still a problem with the pip packages

```shell
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by eljeffeg** [comment]
You need to run the python `pip3` install as a normal user, non-root.  The new depends.sh will create a virtual environment `.venv` for python so it should work fine.

I added a new `start.sh` file as well to make sure the virtual environment is activated after reboot.

I did install both mysql-server and sqlite.  Not sure if that was the right choice, but covers all bases.

**Comment by quade0** [comment]
Your are right.
I had to change the permission for the .venv directory after running sudo depends.sh. Run it by non-root user.
Sqlite or mysql-server should be selectable with a option by running the depends.sh.

I still had some issues

Steps to reproduce:

```shell
cd /opt/RootTheBox
git pull
git log -1
sudo chown $USER: -R /opt/RootTheBox
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r setup/requirements.txt --upgrade
./rootthebox.py --setup=prod --sql-dialect=sqlite
./rootthebox.py --start --log_file_prefix=./files/rtb.log
``` 

After the installation I could not log in with the default credentials into the ui.

I tryed to reset the password:

```shell
./rootthebox.py --recovery
Traceback (most recent call last):
  File "/opt/RootTheBox/./rootthebox.py", line 1232, in <module>
    recovery()
  File "/opt/RootTheBox/./rootthebox.py", line 134, in recovery
    from setup.recovery import RecoveryConsole
  File "/opt/RootTheBox/setup/recovery.py", line 36, in <module>
    from setup.create_database import User, Team, Permission
ImportError: cannot import name 'User' from 'setup.create_database' (/opt/RootTheBox/setup/create_database.py)
```

**Comment by eljeffeg** [comment]
Thanks for testing.. I pushed some additional updates and a new `setup/setup.sh` that should hopefully do better at handling the different permissions.  Run it as a normal user and it will sudo the depends.sh.  Fixed the recovery and made some changes to the bootstrap.  I automatically create the default admin user - figured you can always change the password or remove the user.  Please give it another test.

**Comment by quade0** [comment]
Thank you for the update.
In my case the .env and the sql_dialect had to be set manually.
The password recovery option is still not working.

Steps to reproduce:

```shell
setup/setup.sh
python3 -m venv .venv
source .venv/bin/activate

python3 ./rootthebox.py --setup=prod --sql-dialect=sqlite
[*] 09:46:43 : Creating the database ...
[*] 09:46:44 : Bootstrapping the database ...
[?] RootTheBox Admin Username [admin]: admin
[?] New Admin Password: 
[?] Confirm New Admin Password: 
[I 250729 09:49:08 __init__:263] Checking for Database Updates...
[I 250729 09:49:08 migration:211] Context impl SQLiteImpl.
[I 250729 09:49:08 migration:214] Will assume non-transactional DDL.
[I 250729 09:49:08 migration:622] Running stamp_revision  -> 1ee5b63e716f
[*] Production bootstrap

python3 ./rootthebox.py --start
[C 250729 09:53:51 DatabaseConnection:151] Cannot connect to database with any available driver. Verify correct username & password in rootthebox.cfg and db dependencies.

vi ./files/rootthebox.cfg
[...]
sql_dialect = "sqlite"
[...]

python3 ./rootthebox.py --start --log_file_prefix=./files/rtb.log
[*] Starting RTB on http://<ip>:8888

http://<ip>:8888/  # Login success

python3 ./rootthebox.py --recovery
Traceback (most recent call last):
  File "/opt/RootTheBox/./rootthebox.py", line 35, in <module>
    from libs.ConfigHelpers import save_config, save_config_image
  File "/opt/RootTheBox/libs/ConfigHelpers.py", line 10, in <module>
    from libs.XSSImageCheck import is_xss_image, detect_image_format
  File "/opt/RootTheBox/libs/XSSImageCheck.py", line 21, in <module>
    from resizeimage import resizeimage
ModuleNotFoundError: No module named 'resizeimage'
```

**Comment by tijldeneut** [comment]
FYI, tested and fully functional on a vanilla Ubuntu 24.04:

```
apt update && apt install -y git sudo
adduser rtb
usermod -aG sudo rtb; su rtb
cd /opt/
sudo git clone --depth=1 --branch 3.15.x https://github.com/moloch--/RootTheBox
sudo chown -R rtb:rtb RootTheBox && cd RootTheBox
sudo ./setup/depends.sh -y SKIP  # non-interactive mode, remove "-y SKIP" to get questions
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r setup/requirements.txt --upgrade

python3 rootthebox.py --save ## Generate 'files/rootthebox.cfg' -> Edit it now

sudo mysql -e "create user 'rtb'@'localhost' identified by 'rtb'"
sudo mysql -e "create database rootthebox character set utf8mb4"
sudo mysql -e "grant all on rootthebox.* to 'rtb'@'localhost'"

python3 rootthebox.py --setup=prod ## Create (initial) database

sudo vi /etc/systemd/system/rtb.service ## Edit the paths below if the location differs
[...]
[Unit]
Description=Root The Box daemon
After=network.target
 
[Service]
Type=simple
User=rtb
Group=rtb
WorkingDirectory=/opt/RootTheBox
ExecStart=/opt/RootTheBox/.venv/bin/python /opt/RootTheBox/rootthebox.py --start
Restart=on-failure
 
[Install]
WantedBy=multi-user.target
[...]

sudo systemctl daemon-reload
sudo systemctl enable --now rtb
sudo systemctl status rtb
#> If it fails because the port is 80 or 443:
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python3.12
```
